    server {
        listen ${SERVER_PORT};
        server_name _;

        root  /usr/share/nginx/html;
        index index.html;

        add_header X-Frame-Options      "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy      "strict-origin-when-cross-origin" always;

        location = /healthz/liveness {
            access_log off;
            return 200 "UP\n";
            add_header Content-Type text/plain;
        }

        location = /healthz/readiness {
            access_log off;
            try_files /index.html =503;
            add_header Content-Type text/plain;
        }
