/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import {
  StaleWhileRevalidate,
  CacheFirst,
  NetworkFirst,
} from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

declare const self: ServiceWorkerGlobalScope;

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// Cache the Google Fonts webfont files with a cache-first strategy for 1 year
registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 30,
      }),
    ],
  })
);

// Cache images with a cache-first strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Cache static assets (JS, CSS) with stale-while-revalidate
registerRoute(
  ({ request }) =>
    request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// Cache API responses with network-first strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
    networkTimeoutSeconds: 10,
  })
);

// Background sync for offline mutations
// Reduced retention and added onSync callback for staleness validation
const MAX_MUTATION_AGE_MS = 2 * 60 * 60 * 1000; // 2 hours (down from 24h)

const bgSyncPlugin = new BackgroundSyncPlugin('api-queue', {
  maxRetentionTime: 120, // 2 hours in minutes
  onSync: async ({ queue }) => {
    // Replay queued requests with staleness check
    let entry;
    while ((entry = await queue.shiftRequest())) {
      try {
        const queuedAt = entry.timestamp;
        // Discard mutations older than MAX_MUTATION_AGE_MS to prevent stale writes
        if (queuedAt && Date.now() - queuedAt > MAX_MUTATION_AGE_MS) {
          console.warn('[SW] Discarding stale queued request:', entry.request.url);
          continue;
        }

        // Clone request and add idempotency key so the server can deduplicate replays
        const idempotencyKey = `sw-${queuedAt}-${entry.request.url}`;
        const headers = new Headers(entry.request.headers);
        headers.set('X-Idempotency-Key', idempotencyKey);
        headers.set('X-Queued-At', String(queuedAt || Date.now()));

        const modifiedRequest = new Request(entry.request, { headers });
        const response = await fetch(modifiedRequest);

        // If the server rejects with 409 Conflict, the mutation was already applied
        if (response.status === 409) {
          console.warn('[SW] Server reported conflict for replayed request, skipping:', entry.request.url);
          continue;
        }

        if (!response.ok) {
          // Re-queue for retry on transient failures
          await queue.unshiftRequest(entry);
          throw new Error(`Replay failed with status ${response.status}`);
        }
      } catch (error) {
        // Put it back and stop processing (will retry later)
        await queue.unshiftRequest(entry);
        throw error;
      }
    }
  },
});

// Queue failed mutating API requests for background sync
const mutationMatcher = ({ url }: { url: URL }) => url.pathname.startsWith('/api/');
const mutationStrategy = new NetworkFirst({ plugins: [bgSyncPlugin] });

registerRoute(mutationMatcher, mutationStrategy, 'POST');
registerRoute(mutationMatcher, mutationStrategy, 'PUT');
registerRoute(mutationMatcher, mutationStrategy, 'DELETE');
registerRoute(mutationMatcher, mutationStrategy, 'PATCH');

// Handle navigation requests (SPA routing)
// Return index.html for all navigation requests
const navigationHandler = new NetworkFirst({
  cacheName: 'navigation-cache',
  plugins: [
    new CacheableResponsePlugin({
      statuses: [0, 200],
    }),
  ],
});

// This is the navigation route
registerRoute(
  new NavigationRoute(navigationHandler, {
    denylist: [/^\/_/, /\/api\//],
  })
);

// Listen for skip waiting message
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Handle push notifications
self.addEventListener('push', (event) => {
  if (!event.data) return;

  const data = event.data.json();

  const options = {
    body: data.body,
    icon: '/icons/icon-192.png',
    badge: '/icons/badge-72.png',
    vibrate: [100, 50, 100],
    data: {
      url: data.url || '/',
    },
    actions: data.actions || [],
    tag: data.tag || 'default',
    renotify: true,
  } as NotificationOptions;

  event.waitUntil(
    self.registration.showNotification(data.title || 'codeSpire solutions', options)
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const url = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((clientList) => {
      // Check if there's already a window open
      for (const client of clientList) {
        if (client.url === url && 'focus' in client) {
          return client.focus();
        }
      }
      // Open new window if none found
      if (self.clients.openWindow) {
        return self.clients.openWindow(url);
      }
    })
  );
});

// Periodic background sync for data refresh
self.addEventListener('periodicsync', (event: any) => {
  if (event.tag === 'sync-data') {
    event.waitUntil(syncData());
  }
});

async function syncData() {
  // Sync latest data in background
  try {
    const response = await fetch('/api/v1/sync/status');
    if (response.ok) {
      const cache = await caches.open('api-cache');
      await cache.put('/api/v1/sync/status', response);
    }
  } catch {
    // Silently fail - will retry on next sync
  }
}

export {};
