# ============================================================================
# PMT + HRMS - one-click local launcher (Windows).
# Double-click Start-PMT-HRMS.bat (which runs this). It will:
#   1. check Docker is installed & running
#   2. generate a .env with strong random secrets + this PC's LAN IP (first run)
#   3. build & start the whole stack
#   4. print the link to share with your team
# ============================================================================
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot            # repo root (parent of installer/)
$compose = Join-Path $root 'docker-compose.local.yml'
$envFile = Join-Path $root '.env'

# Shared IP-detection / config-update helpers (same code the logon task uses).
. (Join-Path $PSScriptRoot '_pmt_common.ps1')

function Write-Step($msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }

# --- 1. Docker check -------------------------------------------------------
# NOTE: PowerShell try/catch does NOT catch a native docker.exe failure, so we
# must check the exit code. `docker info` only returns 0 when the engine is
# actually running (a stopped Docker Desktop returns a non-zero code).
Write-Step 'Checking Docker...'
$dockerRunning = $false
try {
  docker info *> $null
  $dockerRunning = ($LASTEXITCODE -eq 0)
} catch {
  $dockerRunning = $false
}
if (-not $dockerRunning) {
  Write-Host ''
  Write-Host '  Docker is NOT running.' -ForegroundColor Red
  Write-Host ''
  Write-Host '  Please:' -ForegroundColor Yellow
  Write-Host '    1. Open Docker Desktop (Start menu -> Docker Desktop).'
  Write-Host '    2. Wait until the whale icon (bottom-right) stops animating / turns steady.'
  Write-Host '    3. Then run Start-PMT-HRMS again.'
  Write-Host ''
  Write-Host '  (If Docker is not installed: https://www.docker.com/products/docker-desktop/)'
  Write-Host ''
  Read-Host 'Press Enter to close'; exit 1
}
Write-Host 'Docker OK.' -ForegroundColor Green

# --- 2. Detect this PC's LAN IP -------------------------------------------
$lanIp = Get-LanIp
Write-Host "This PC's address on the office network: $lanIp"

# --- 3. Generate .env on first run ----------------------------------------
function New-Secret([int]$len = 48) {
  -join ((48..57) + (65..90) + (97..122) | Get-Random -Count $len | ForEach-Object { [char]$_ })
}

if (-not (Test-Path $envFile)) {
  Write-Step 'First run - generating configuration (.env) with secure secrets...'
  $adminPass = New-Secret 12
  @"
# Auto-generated by the installer. Keep this file private.
NODE_ENV=production
LOG_LEVEL=info

# Default administrator (change the password after first login)
ADMIN_EMAIL=admin@local.host
ADMIN_PASSWORD=$adminPass

# Secrets
JWT_SECRET=$(New-Secret 48)
JWT_REFRESH_SECRET=$(New-Secret 48)
DATABASE_PASSWORD=$(New-Secret 24)
DATABASE_NAME=projectflow
DATABASE_USER=postgres

# LAN access (team members reach the app at these addresses)
PUBLIC_HOST=$lanIp
FRONTEND_URL=http://${lanIp}:3001
HRMS_FRONTEND_URL=http://${lanIp}:3000
CORS_ORIGINS=http://${lanIp}:3000,http://${lanIp}:3001,http://localhost:3000,http://localhost:3001

# Attendance rules (edit these then restart to apply)
COMPANY_TIMEZONE=Asia/Kolkata
FULL_DAY_HOURS=9
HALF_DAY_HOURS=4
OFFICE_START_TIME=09:30

# Optional integrations (leave blank = feature off)
OPENAI_API_KEY=
SMTP_HOST=
SMTP_USER=
SMTP_PASSWORD=
"@ | Set-Content -Path $envFile -Encoding UTF8
  Write-Host 'Configuration created.' -ForegroundColor Green
  Write-Host ''
  Write-Host '  ----------------------------------------------------------------' -ForegroundColor Yellow
  Write-Host '   FIRST-TIME ADMIN LOGIN' -ForegroundColor Yellow
  Write-Host "     Email:    admin@local.host" -ForegroundColor Yellow
  Write-Host "     Password: $adminPass" -ForegroundColor Yellow
  Write-Host '   (Save this. Change the password after logging in.)' -ForegroundColor Yellow
  Write-Host '  ----------------------------------------------------------------' -ForegroundColor Yellow
} else {
  Write-Host 'Using existing configuration (.env).'
  # The host's IP can change (new DHCP lease after a reboot/router restart). Keep
  # the team link + CORS pointed at the CURRENT address on every launch.
  if (Update-EnvIp $envFile $lanIp) {
    Write-Host "Network address changed - team link updated to: $lanIp" -ForegroundColor Green
  }
}

# --- 4. Build & start ------------------------------------------------------
Write-Step 'Starting PMT + HRMS (first run downloads/builds - this can take several minutes)...'
docker compose -f $compose up -d --build

# --- 5. Wait for the API to be healthy ------------------------------------
Write-Step 'Waiting for the application to be ready...'
$ready = $false
for ($i = 0; $i -lt 60; $i++) {
  try {
    $s = (docker compose -f $compose ps --format '{{.Service}} {{.Status}}' | Select-String '^api ')
    if ($s -match 'healthy') { $ready = $true; break }
  } catch {}
  Start-Sleep -Seconds 5
}

Write-Host ''
if ($ready) {
  Write-Host '================================================================' -ForegroundColor Green
  Write-Host '  PMT + HRMS is RUNNING' -ForegroundColor Green
  Write-Host '================================================================' -ForegroundColor Green
  Write-Host ''
  Write-Host '  Share these links with your team (same office network):'
  Write-Host "     Project Management (PMT):  http://${lanIp}:3001" -ForegroundColor White
  Write-Host "     HR Management (HRMS):      http://${lanIp}:3000" -ForegroundColor White
  Write-Host ''
  Write-Host "  On this PC you can also use http://localhost:3001 / :3000"
} else {
  Write-Host 'The app is taking longer than expected to start.' -ForegroundColor Yellow
  Write-Host 'Check status with:  docker compose -f docker-compose.local.yml ps'
  Write-Host 'View logs with:     docker compose -f docker-compose.local.yml logs -f api'
}
Write-Host ''
Read-Host 'Press Enter to close this window (the app keeps running in the background)'
